### ISSUE TITLE
Lua error with "old guild panel" since 11.0.5

### ISSUE THREAD

**Issue by reaper666735** [millanzarreta/ClassicUI#5]
Hello,

since patch 11.0.5 the older guild pane only throws errors and a guild full of nameless warriors :p , 

16x ...assicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua:32: attempt to concatenate local 'onlineAndMobileMembers' (a nil value)
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua"]:32: in function <...assicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua:7>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ClassicUI/ClassicUI.lua"]:9354: in function `ToggleOldGuildFrame'
[string "@ClassicUI/ClassicUI.lua"]:9375: in function <ClassicUI/ClassicUI.lua:9372>
[string "=[C]"]: in function `ToggleGuildFrame'
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:988: in function <...zzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua:986>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
self = CUI_GuildFrame {
 numTabs = 5
 nameAlert = CUI_GuildNameChangeFrame {
 }
 hasForcedNameChange = false
 NineSlice = Frame {
 }
 layoutType = "PortraitFrameTemplate"
 TitleMouseover = Frame {
 }
 Inset = CUI_GuildFrameInset {
 }
 PortraitContainer = Frame {
 }
 TopTileStreaks = Texture {
 }
 Bg = CUI_GuildFrameBg {
 }
 TitleContainer = Frame {
 }
 CloseButton = CUI_GuildFrameCloseButton {
 }
 Tabs = <table> {
 }
}
guildName = "Little Blood Angels"
_ = "Guild Master"
_ = 0
realm = nil
fullName = "Little Blood Angels"
totalMembers = 307
onlineMembers = 1
onlineAndMobileMembers = nil
(*temporary) = CUI_GuildFrameMembersCount {
}
(*temporary) = nil
(*temporary) = " / 307"
(*temporary) = "307"
(*temporary) = "attempt to concatenate local 'onlineAndMobileMembers' (a nil value)"

--------------------------------------------

483x ...assicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua:83: attempt to concatenate local 'onlineAndMobileMembers' (a nil value)
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua"]:83: in function <...assicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua:80>

Locals:
self = CUI_GuildFrame {
 nameAlert = CUI_GuildNameChangeFrame {
 }
 TitleMouseover = Frame {
 }
 TitleContainer = Frame {
 }
 Tabs = <table> {
 }
 layoutType = "PortraitFrameTemplate"
 PortraitContainer = Frame {
 }
 Bg = CUI_GuildFrameBg {
 }
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 CloseButton = CUI_GuildFrameCloseButton {
 }
 numTabs = 5
 hasForcedNameChange = false
 selectedTab = 2
 Inset = CUI_GuildFrameInset {
 }
}
event = "GUILD_ROSTER_UPDATE"
totalMembers = 307
onlineMembers = 1
onlineAndMobileMembers = nil
(*temporary) = CUI_GuildFrameMembersCount {
}
(*temporary) = nil
(*temporary) = " / 307"
(*temporary) = "307"
(*temporary) = "attempt to concatenate local 'onlineAndMobileMembers' (a nil value)"

----------------------------------------------

25x ...cUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildRoster.lua:253: attempt to compare number with nil
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildRoster.lua"]:253: in function `CUI_GuildRoster_Update'
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildRoster.lua"]:89: in function <...cUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildRoster.lua:87>
[string "=[C]"]: in function `Show'
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua"]:281: in function `CUI_GuildFrame_ShowPanel'
[string "@ClassicUI_ClassicBlizzGuildUI/CUI_Blizzard_GuildUI.lua"]:336: in function `CUI_GuildFrame_TabClicked'
[string "*CUI_Blizzard_GuildUI.xml:308_OnClick"]:1: in function <[string "*CUI_Blizzard_GuildUI.xml:308_OnClick"]:1>

Locals:
scrollFrame = CUI_GuildRosterContainer {
 buttons = <table> {
 }
 ScrollChild = CUI_GuildRosterContainerScrollChild {
 }
 scrollUp = CUI_GuildRosterContainerScrollBarScrollUpButton {
 }
 scrollDown = CUI_GuildRosterContainerScrollBarScrollDownButton {
 }
 offset = 0
 scrollBar = CUI_GuildRosterContainerScrollBar {
 }
 buttonHeight = 22
 scrollChild = CUI_GuildRosterContainerScrollChild {
 }
}
offset = 0
buttons = <table> {
 1 = CUI_GuildRosterContainerButton1 {
 }
 2 = CUI_GuildRosterContainerButton2 {
 }
 3 = CUI_GuildRosterContainerButton3 {
 }
 4 = CUI_GuildRosterContainerButton4 {
 }
 5 = CUI_GuildRosterContainerButton5 {
 }
 6 = CUI_GuildRosterContainerButton6 {
 }
 7 = CUI_GuildRosterContainerButton7 {
 }
 8 = CUI_GuildRosterContainerButton8 {
 }
 9 = CUI_GuildRosterContainerButton9 {
 }
 10 = CUI_GuildRosterContainerButton10 {
 }
 11 = CUI_GuildRosterContainerButton11 {
 }
 12 = CUI_GuildRosterContainerButton12 {
 }
 13 = CUI_GuildRosterContainerButton13 {
 }
 14 = CUI_GuildRosterContainerButton14 {
 }
 15 = CUI_GuildRosterContainerButton15 {
 }
 16 = CUI_GuildRosterContainerButton16 {
 }
}
numButtons = 16
button = CUI_GuildRosterContainerButton1 {
 stripe = CUI_GuildRosterContainerButton1Stripe {
 }
 barTexture = CUI_GuildRosterContainerButton1BarTexture {
 }
 header = CUI_GuildRosterContainerButton1HeaderButton {
 }
 barLabel = CUI_GuildRosterContainerButton1BarLabel {
 }
 string1 = CUI_GuildRosterContainerButton1String1 {
 }
 string4 = CUI_GuildRosterContainerButton1String4 {
 }
 string2 = CUI_GuildRosterContainerButton1String2 {
 }
 icon = CUI_GuildRosterContainerButton1Icon {
 }
 string3 = CUI_GuildRosterContainerButton1String3 {
 }
}
index = 1
class = nil
totalMembers = 307
onlineMembers = 1
onlineAndMobileMembers = nil
selectedGuildMember = 0
guildName = "Little Blood Angels"
guildRankName = "Guild Master"
guildRankIndex = 0
maxRankIndex = 6
fullName = nil
rank = nil
rankIndex = 0
level = 0
class = nil
zone = nil
note = nil
officernote = nil
online = nil
isAway = ""
classFileName = nil
achievementPoints = 0
achievementRank = 0
isMobile = false
maxAchievementsPoints = 19510
visibleMembers = nil
(for index) = 1
(for limit) = 16
(for step) = 1
i = 1
fullName = "Blondegast-Lightbringer"
rank = "Guild Master"
rankIndex = 0
level = 80
class = "Paladin"
zone = "Tanaris"
note = "Mining and skinn : Main"
officernote = "Guildmaster Kevin,B"
online = true
isAway = 0
classFileName = "PALADIN"
achievementPoints = 19510
achievementRank = 1
isMobile = false
canSoR = false
repStanding = 8
onlineOrMobile = true
(*temporary) = 8
(*temporary) = "Player-1388-00ADCD72"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
currentGuildView = "playerStatus"
MOBILE_BUSY_ICON = "|TInterface\ChatFrame\UI-ChatIcon-ArmoryChat-BusyMobile:14:14:0:0:16:16:0:16:0:16|t"
MOBILE_AWAY_ICON = "|TInterface\ChatFrame\UI-ChatIcon-ArmoryChat-AwayMobile:14:14:0:0:16:16:0:16:0:16|t"
GUILD_DETAIL_OFFICER_HEIGHT = 228
GUILD_DETAIL_NORM_HEIGHT = 175
GUILD_ROSTER_BAR_MAX = 239
GUILD_ROSTER_BUTTON_HEIGHT = 20
GUILD_ROSTER_BUTTON_OFFSET = 2

**Comment by millanzarreta** [comment]
Thanks for reporting this error. It is fixed in the new v2.1.0 version.
